export EDITOR="/usr/local/bin/mate -w"                                                                    
alias code="cd ~/Desktop/codeforces"                                                                      
alias codea="cat t.cpp > a.cpp"                                                                           
alias codeb="cat t.cpp > b.cpp"
alias codec="cat t.cpp > c.cpp"                                                                           
alias coded="cat t.cpp > d.cpp"
alias codee="cat t.cpp > e.cpp"
alias c="g++ -std=c++17 -Wall -Wextra -O2"
alias caa="c a.cpp -o a;./a"
alias cbb="c b.cpp -o b;./b"
alias ccc="c c.cpp -o c;./c"
alias cdd="c d.cpp -o d;./d"
alias cee="c e.cpp -o e;./e"
alias ct="echo $() > a.cpp:tests;echo $() > b.cpp:tests;echo $() > c.cpp:tests;echo $() > d.cpp:tests;echo
 $() > e.cpp:tests"
alias prep="code;codea;codeb;codec;coded;codee;ct"
